baseURL = 'https://yixiapp.com/'
languageCode = 'en-us'
title = '一席桑麻的笔记本'
theme = 'PaperMod'
publishDir = "docs"
[taxonomies]
tag = "tags"
category = "categories"
[params]
  defaultTheme = "auto"
  disableThemeToggle = "true"
[[menu.main]]
  weight = 1
  identifier = "posts"
  pre = ""
  post = ""
  name = "归档"
  url = "/posts/"
  title = "Posts"
[[menu.main]]
  weight = 2
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = "Tags"
[[menu.main]]
  weight = 3
  identifier = "categories"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = "Categories"
[search]
  enable = true
  type = "algolia"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 50
  highlightTag = "em"
  absoluteURL = false
  [search.algolia]
    index = ""
    appID = ""
    searchKey = ""
[footer]
  enable = true
  # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
  custom = ''
  # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
  hugo = false
  # LoveIt 新增 | 0.2.0 是否显示版权信息
  copyright = true
  # LoveIt 新增 | 0.2.0 是否显示作者
  author = true
  # 网站创立年份
  since = 2023
  # ICP 备案信息，仅在中文显示
  icp = '沪ICP备18043359号-1' 
  # 许可协议信息 (支持 HTML 格式)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>' 
[home]
  rss = 10
  [home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 8
  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/avatar.png"
    title = ""
    subtitle = ""
    typeit = true
    social = true
    disclaimer = ""
[social]
  GitHub = ""
  Weibo = ""
  Steam = ""
  Zhihu = ""
  Douban = ""
  Devto = ""
  Bilibili = ""
  Email = ""
  Phone = ""
  RSS = true
